image: gitpod/workspace-dotnet

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Setup Git email
    before: |
      git config --global --unset user.email
      git config --global --add user.email 63785730+welamic@users.noreply.github.com

  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
